repos:
    - repo: https://github.com/psf/black
      rev: 19.10b0
      hooks:
        - id: black
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.5.0
      hooks:
        - id: check-added-large-files
          args: ['--maxkb=80000']
        - id: trailing-whitespace
        - id: check-xml
        - id: end-of-file-fixer
